name: Deploy JMeter Scripts

on:
  workflow_call:
    inputs:
      jmeter-test-node:
        description: "Target JMeter machine (e.g., 10.0.0.10)"
        required: true
        type: string
      jmeter-test-path:
        description: "Path to the JMeter test files"
        required: true
        type: string
      powershell-path:
        description: "Path to PowerShell scripts"
        required: true
        type: string
      login-user:
        description: "Remote login username"
        required: true
        type: string

jobs:
  deploy-jmeter:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy JMeter scripts
        shell: pwsh
        run: |
          Write-Host "Deploying JMeter scripts to ${{ inputs.jmeter-test-node }}"
          $arguments = @(
            '-Servers', "${{ inputs.jmeter-test-node }}",
            '-JmeterTestPath', "${{ inputs.jmeter-test-path }}",
            '-PowershellPath', "${{ inputs.powershell-path }}",
            '-User', "${{ inputs.login-user }}",
            '-Password', "${{ secrets.login-password }}"
          )

          & ./PowerShell/Jmeter/DeployJmeterScripts.ps1 @arguments
        continue-on-error: true
