name: Deploy JMeter Scripts

on:
  workflow_call:
    inputs:
      jmeter-test-node:
        required: true
        type: string
      jmeter-test-path:
        required: true
        type: string
      powershell-path:
        required: true
        type: string
      login-user:
        required: true
        type: string
    secrets:
      login-password:
        required: true

jobs:
  deploy-jmeter:
    runs-on: [self-hosted, performance-engineering]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy JMeter scripts
        shell: pwsh
        run: |
          Write-Host "Deploying JMeter scripts to ${{ inputs.jmeter-test-node }}"
          $arguments = @(
            '-Servers', "${{ inputs.jmeter-test-node }}",
            '-JmeterTestPath', "${{ inputs.jmeter-test-path }}",
            '-PowershellPath', "${{ inputs.powershell-path }}",
            '-User', "${{ inputs.login-user }}",
            '-Password', "${{ secrets.login-password }}"
          )

          & ./PowerShell/Jmeter/DeployJmeterScripts.ps1 @arguments
        continue-on-error: true
