name: Integration Studio Mars

on:
  workflow_dispatch: # Manual trigger for now
    inputs:
      jmeter-test-node:
        description: "Target JMeter machine $JmeterTestingSingleNode"
        required: true
        type: string
      jmeter-test-path:
        description: "Path to the JMeter test files $JmeterTestPath"
        required: true
        type: string
      powershell-path:
        description: "Path to PowerShell scripts $PowershellPath"
        required: true
        type: string
      login-user:
        description: "Remote login username $LoginUserCustadds"
        required: true
        type: string
      env-name:
        description: "Environment name $Envname"
        required: true
        type: string
      is-automation:
        description: "Is this an automation run? (true/false) $IsAutomation"
        required: true
        type: boolean
      is-scheduled:
        description: "Is this a scheduled run? (true/false) $IsScheduled"
        required: true
        type: boolean
      pwsh:
        description: "Path to PowerShell executable $pwsh"
        required: true
        type: string
    secrets:
      login-password:
        required: true

jobs:
  deploy-scripts:
    uses: meer1616/integration-studio-mars/.github/workflows/Deploy_JMeter_Script_Reusable.yml@main
    with:
      jmeter-test-node: ${{ github.event.inputs.jmeter-test-node }}
      jmeter-test-path: ${{ github.event.inputs.jmeter-test-path }}
      powershell-path: ${{ github.event.inputs.powershell-path }}
      login-user: ${{ github.event.inputs.login-user }}
    secrets:
      login-password: ${{ secrets.LOGIN_PASSWORD }}

  run-integrationstudio-test:
    uses: meer1616/integration-studio-mars/.github/workflows/IntegrationStudio_ECKSSO_LOAD.yml@main
    needs: deploy-scripts
    with:
      env-name: ${{ github.event.inputs.env-name }}
      is-automation: ${{ github.event.inputs.is-automation }}
      is-scheduled: ${{ github.event.inputs.is-scheduled }}
      pwsh: ${{ github.event.inputs.pwsh }}
