name: Integration Studio Mars

on:
  workflow_dispatch: # Manual trigger for now

jobs:
  deploy-scripts:
    uses: meer1616/integration-studio-mars/.github/workflows/Deploy_JMeter_Script_Reusable.yml@main
    with:
      jmeter-test-node: ${{ github.event.inputs.jmeter-test-node }}
      jmeter-test-path: ${{ github.event.inputs.jmeter-test-path }}
      powershell-path: ${{ github.event.inputs.powershell-path }}
      login-user: ${{ github.event.inputs.login-user }}
    secrets:
      login-password: ${{ secrets.LOGIN_PASSWORD }}
