name: Integration Studio Mars

on:
  workflow_dispatch: # Manual trigger for now
    inputs:
      jmeter-test-node:
        description: "Target JMeter machine (e.g., 10.0.0.10)"
        required: true
        type: string
      jmeter-test-path:
        description: "Path to the JMeter test files"
        required: true
        type: string
      powershell-path:
        description: "Path to PowerShell scripts"
        required: true
        type: string
      login-user:
        description: "Remote login username"
        required: true
        type: string
    secrets:
      login-password:
        required: true

jobs:
  deploy-scripts:
    uses: meer1616/integration-studio-mars/.github/workflows/Deploy_JMeter_Script_Reusable.yml@main
    with:
      jmeter-test-node: ${{ github.event.inputs.jmeter-test-node }}
      jmeter-test-path: ${{ github.event.inputs.jmeter-test-path }}
      powershell-path: ${{ github.event.inputs.powershell-path }}
      login-user: ${{ github.event.inputs.login-user }}
    secrets:
      login-password: ${{ secrets.LOGIN_PASSWORD }}
